# Generated by Django 2.1.8 on 2019-09-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=32)),
                ('goods_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='good_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='seller/images/banner01.jpg', upload_to='seller/images'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType'),
        ),
    ]
