# Generated by Django 2.1.8 on 2019-09-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20190909_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_produce_time',
            field=models.DateField(),
        ),
    ]
