# Generated by Django 2.1.8 on 2019-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_auto_20190909_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
