# Generated by Django 2.1.8 on 2019-09-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20190909_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='picture',
            new_name='goods_picture',
        ),
    ]
