# Generated by Django 2.1.8 on 2019-09-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20190909_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='goods_type_picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
