# Generated by Django 2.1.8 on 2019-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_goodstype_goods_type_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_details',
            field=models.ImageField(default='物美价廉，欢迎品尝', upload_to=''),
        ),
    ]
