# Generated by Django 2.1.8 on 2019-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_goods_goods_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.CharField(max_length=32)),
                ('code_email', models.EmailField(max_length=254)),
                ('code_status', models.IntegerField(default=0)),
                ('code_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
