# Generated by Django 2.1.8 on 2019-09-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_validcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_store',
            new_name='goods_store',
        ),
    ]
