# Generated by Django 2.1.8 on 2019-09-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0008_goods_goods_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_data', models.DateField(auto_now=True)),
                ('order_status', models.IntegerField(default=0)),
                ('order_money', models.FloatField(blank=True, null=True)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_picture', models.CharField(max_length=32)),
                ('goods_count', models.IntegerField()),
                ('goods_price', models.FloatField()),
                ('goods_total_price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Order')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.User')),
            ],
        ),
    ]
